
const emojiList = [
  {type: 'people', name: 'smile', emoji: '😄'}, 
  {type: 'people', name: 'laughing', emoji: '😆'},
  {type: 'people', name: 'blush', emoji: '😊'},
  {type: 'people', name: 'smiley', emoji: '😃'},
  {type: 'people', name: 'smirk', emoji: '😏'},
  {type: 'people', name: 'heart_eyes', emoji: '😍'},
  {type: 'people', name: 'kissing_heart', emoji: '😘'},
  {type: 'people', name: 'kissing_closed_eyes', emoji: '😚'},
  {type: 'people', name: 'flushed', emoji: '😳'},
  {type: 'people', name: 'relieved', emoji: '😌'},
  {type: 'people', name: 'grin', emoji: '😁'},
  {type: 'people', name: 'smiling_face_with_tear',emoji: '🥲'},
  {type: 'people', name: 'wink',emoji: '😉'},
  {type: 'people', name: 'stuck_out_tongue', emoji: '😛'},
  {type: 'people', name: 'sleeping', emoji: '😴'},
  {type: 'people', name: 'worried', emoji: '😟'},
  {type: 'people', name: 'open_mouth', emoji: '😮'},
  {type: 'people', name: 'confused', emoji: '😕'},
  {type: 'people', name: 'expressionless', emoji: '😑'},
  {type: 'people', name: 'neutral_face', emoji: '😐'},
  {type: 'people', name: 'sweat_smile', emoji: '😅'},
  {type: 'people', name: 'weary', emoji: '😩'},
  {type: 'people', name: 'pensive', emoji: '😔'},
  {type: 'people', name: 'disappointed', emoji: '😞'},
  {type: 'people', name: 'thinking', emoji: '🤔'},
  {type: 'people', name: 'fearful', emoji: '😨'},
  {type: 'people', name: 'cry', emoji: '😢'},
  {type: 'people', name: 'sob',emoji: '😭'},
  {type: 'people', name: 'joy',emoji: '😂'},
  {type: 'people', name: 'scream',emoji: '😱'},
  {type: 'people', name: 'angry',emoji: '😠'},
  {type: 'people', name: 'rage',emoji: '😡'},
  {type: 'people', name: 'cursing_face',emoji: '🤬'},
  {type: 'people', name: 'triumph',emoji: '😤'},
  {type: 'people', name: 'sleepy',emoji: '😪'},
  {type: 'people', name: 'sleeping',emoji: '😴'},
  {type: 'people', name: 'yum',emoji: '😋'},
  {type: 'people', name: 'stuck_out_tongue',emoji: '😛'},
  {type: 'people', name: 'zany_face',emoji: '🤪'},
  {type: 'people', name: 'shushing_face',emoji: '🤫'},
  {type: 'people', name: 'zipper_mouth_face',emoji: '🤐'},
  {type: 'people', name: 'face_in_clouds',emoji: '😶‍🌫️'},
  {type: 'people', name: 'roll_eyes',emoji: '🙄'},
  {type: 'people', name: 'lying_face',emoji: '🤥'},
  {type: 'people', name: 'face_with_thermometer',emoji: '🤒'},
  {type: 'people', name: 'face_with_head_bandage',emoji: '🤕'},
  {type: 'people', name: 'nauseated_face',emoji: '🤢'},
  {type: 'people', name: 'vomiting_face',emoji: '🤮'},
  {type: 'people', name: 'sneezing_face',emoji: '🤧'},
  {type: 'people', name: 'hot_face',emoji: '🥵'},
  {type: 'people', name: 'cold_face',emoji: '🥶'},
  {type: 'people', name: 'woozy_face',emoji: '🥴'},
  {type: 'people', name: 'dizzy_face',emoji: '😵'},
  {type: 'people', name: 'face_with_spiral_eyes',emoji: '😵‍💫'},
  {type: 'people', name: 'exploding_head',emoji: '🤯'},
  {type: 'people', name: 'cowboy_hat_face',emoji: '🤠'},
  {type: 'people', name: 'partying_face',emoji: '🥳'},
  {type: 'people', name: 'disguised_face',emoji: '🥸'},
  {type: 'people', name: 'sunglasses',emoji: '😎'},
  {type: 'people', name: 'nerd_face',emoji: '🤓'},
  {type: 'people', name: 'monocle_face',emoji: '🧐'},
  {type: 'people', name: 'mask',emoji: '😷'},
  {type: 'people', name: 'innocent',emoji: '😇'},
  {type: 'people', name: 'money_mouth_face',emoji: '🤑'},
  {type: 'people', name: 'alien',emoji: '👽'},
  {type: 'people', name: 'clown_face',emoji: '🤡'},
  {type: 'people', name: 'robot',emoji: '🤖'},
  {type: 'people', name: 'space_invader',emoji: '👾'},

  {type: 'people', name: 'walking',emoji: '🚶'},
  {type: 'people', name: 'runner',emoji: '🏃'},
  {type: 'people', name: 'couple',emoji: '👫'},
  {type: 'people', name: 'family',emoji: '👪'},
  {type: 'people', name: 'dancer',emoji: '💃'},
  {type: 'people', name: 'dancers',emoji: '👯'},
  {type: 'people', name: 'raising_hand',emoji: '🙋'},
  {type: 'people', name: 'bow',emoji: '🙇'},
  {type: 'people', name: 'boy',emoji: '👦'},
  {type: 'people', name: 'girl',emoji: '👧'},
  {type: 'people', name: 'woman',emoji: '👩'},
  {type: 'people', name: 'man',emoji: '👨'},
  {type: 'people', name: 'baby',emoji: '👶'},
  {type: 'people', name: 'older_woman',emoji: '👵'},
  {type: 'people', name: 'older_man',emoji: '👴'},
  {type: 'people', name: 'cop',emoji: '👮'},
  {type: 'people', name: 'detective',emoji: '🕵️'},
  {type: 'people', name: 'mermaid',emoji: '🧜‍♀️'},
  {type: 'people', name: 'person_fencing',emoji: '🤺'},
  {type: 'people', name: 'selfie',emoji: '🤳'},
  {type: 'people', name: 'angel',emoji: '👼'},
  {type: 'people', name: 'smiley_cat',emoji: '😺'},
  {type: 'people', name: 'smile_cat',emoji: '😸'},
  {type: 'people', name: 'heart_eyes_cat',emoji: '😻'},
  {type: 'people', name: 'kissing_cat',emoji: '😽'},
  {type: 'people', name: 'smirk_cat',emoji: '😼'},
  {type: 'people', name: 'scream_cat',emoji: '🙀'},
  {type: 'people', name: 'crying_cat_face',emoji: '😿'},
  {type: 'people', name: 'joy_cat',emoji: '😹'},
  {type: 'people', name: 'pouting_cat',emoji: '😾'},
  {type: 'people', name: 'japanese_ogre',emoji: '👹'},
  {type: 'people', name: 'japanese_goblin',emoji: '👺'},
  {type: 'people', name: 'see_no_evil',emoji: '🙈'},
  {type: 'people', name: 'hear_no_evil',emoji: '🙉'},
  {type: 'people', name: 'speak_no_evil',emoji: '🙊'},
  {type: 'people', name: 'guardsman',emoji: '💂‍♂️'},
  {type: 'people', name: 'skull',emoji: '💀'},
  {type: 'people', name: 'skull_and_crossbones',emoji: '☠️'},
  {type: 'people', name: 'feet',emoji: '🐾'},
  {type: 'people', name: 'lips',emoji: '👄'},
  {type: 'people', name: 'kiss',emoji: '💋'},
  {type: 'people', name: 'love_letter',emoji: '💌'},
  {type: 'people', name: 'droplet',emoji: '💧'},
  {type: 'people', name: 'speech_balloon',emoji: '💬'},
  {type: 'people', name: 'thought_balloon',emoji: '💭'},
  {type: 'people', name: 'ear',emoji: '👂'},
  {type: 'people', name: 'ear_with_hearing_aid',emoji: '🦻'},
  {type: 'people', name: 'eyes',emoji: '👀'},
  {type: 'people', name: 'eye',emoji: '👁️'},
  {type: 'people', name: 'nose',emoji: '👃'},
  {type: 'people', name: 'tongue',emoji: '👅'},
  {type: 'people', name: 'muscle',emoji: '💪'},
  {type: 'people', name: 'mechanical_arm',emoji: '🦾'},
  {type: 'people', name: 'mechanical_leg',emoji: '🦿'},
  {type: 'people', name: 'leg',emoji: '🦵'},
  {type: 'people', name: 'foot',emoji: '🦶'},
  {type: 'people', name: 'brain',emoji: '🧠'},
  {type: 'people', name: 'anatomical_heart',emoji: '🫀'},
  {type: 'people', name: 'lungs',emoji: '🫁'},
  {type: 'people', name: 'tooth',emoji: '🦷'},
  {type: 'people', name: 'bone',emoji: '🦴'},

  {type: 'people', name: '+1',emoji: '👍'},
  {type: 'people', name: 'thumbsup',emoji: '👍'},
  {type: 'people', name: '-1',emoji: '👎'},
  {type: 'people', name: 'thumbsdown',emoji: '👎'},
  {type: 'people', name: 'ok_hand',emoji: '👌'},
  {type: 'people', name: 'wave',emoji: '👋'},
  {type: 'people', name: 'punch',emoji: '👊'},
  {type: 'people', name: 'v',emoji: '✌️'},
  {type: 'people', name: 'open_hands',emoji: '👐'},
  {type: 'people', name: 'point_up',emoji: '☝️'},
  {type: 'people', name: 'point_down',emoji: '👇'},
  {type: 'people', name: 'raised_hands',emoji: '🙌'},
  {type: 'people', name: 'pray',emoji: '🙏'},
  {type: 'people', name: 'clap',emoji: '👏'},
  {type: 'people', name: 'metal',emoji: '🤘'},
  {type: 'people', name: 'fu',emoji: '🖕'},

  {type: 'people', name: 'fire',emoji: '🔥'},
  {type: 'people', name: 'poop',emoji: '💩'},
  {type: 'people', name: 'yellow_heart',emoji: '💛'},
  {type: 'people', name: 'blue_heart',emoji: '💙'},
  {type: 'people', name: 'purple_heart',emoji: '💜'},
  {type: 'people', name: 'heart',emoji: '❤️'},
  {type: 'people', name: 'green_heart',emoji: '💚'},
  {type: 'people', name: 'broken_heart',emoji: '💔'},
  {type: 'people', name: 'heartbeat',emoji: '💓'},
  {type: 'people', name: 'heartpulse',emoji: '💗'},
  {type: 'people', name: 'two_hearts',emoji: '💕'},
  {type: 'people', name: 'cupid',emoji: '💘'},
  {type: 'people', name: 'sparkling_heart',emoji: '💖'},
  {type: 'people', name: 'sparkles',emoji: '✨'},
  {type: 'people', name: 'star',emoji: '⭐'},
  {type: 'people', name: 'star2',emoji: '🌟'},
  {type: 'people', name: 'dizzy',emoji: '💫'},
  {type: 'people', name: 'boom',emoji: '💥'},
  {type: 'people', name: 'anger',emoji: '💢'},
  {type: 'people', name: 'exclamation',emoji: '❗'},
  {type: 'people', name: 'question',emoji: '❓'},
  {type: 'people', name: 'grey_exclamation',emoji: '❕'},
  {type: 'people', name: 'grey_question',emoji: '❔'},
  {type: 'people', name: 'zzz',emoji: '💤'},
  {type: 'people', name: 'dash',emoji: '💨'},
  {type: 'people', name: 'sweat_drops',emoji: '💦'},
  {type: 'people', name: 'notes',emoji: '🎶'},
  {type: 'people', name: 'musical_note',emoji: '🎵'},

  {type: 'nature', name: 'sunny',emoji: '☀️'},
  {type: 'nature', name: 'umbrella',emoji: '☔'},
  {type: 'nature', name: 'cloud',emoji: '☁️'},
  {type: 'nature', name: 'snowflake',emoji: '❄️'},
  {type: 'nature', name: 'snowman',emoji: '⛄'},
  {type: 'nature', name: 'zap',emoji: '⚡'},
  {type: 'nature', name: 'cyclone',emoji: '🌀'},
  {type: 'nature', name: 'foggy',emoji: '🌁'},
  {type: 'nature', name: 'ocean',emoji: '🌊'},
  {type: 'nature', name: 'cat',emoji: '🐱'},
  {type: 'nature', name: 'dog',emoji: '🐶'},
  {type: 'nature', name: 'mouse',emoji: '🐭'},
  {type: 'nature', name: 'hamster',emoji: '🐹'},
  {type: 'nature', name: 'rabbit',emoji: '🐰'},
  {type: 'nature', name: 'wolf',emoji: '🐺'},
  {type: 'nature', name: 'frog',emoji: '🐸'},
  {type: 'nature', name: 'tiger',emoji: '🐯'},
  {type: 'nature', name: 'lion',emoji: '🦁'},
  {type: 'nature', name: 'koala',emoji: '🐨'},
  {type: 'nature', name: 'bear',emoji: '🐻'},
  {type: 'nature', name: 'pig',emoji: '🐷'},
  {type: 'nature', name: 'pig_nose',emoji: '🐽'},
  {type: 'nature', name: 'cow',emoji: '🐮'},
  {type: 'nature', name: 'boar',emoji: '🐗'},
  {type: 'nature', name: 'monkey_face',emoji: '🐵'},
  {type: 'nature', name: 'monkey',emoji: '🐒'},
  {type: 'nature', name: 'horse',emoji: '🐴'},
  {type: 'nature', name: 'racehorse',emoji: '🐎'},
  {type: 'nature', name: 'camel',emoji: '🐫'},
  {type: 'nature', name: 'sheep',emoji: '🐑'},
  {type: 'nature', name: 'elephant',emoji: '🐘'},
  {type: 'nature', name: 'beaver',emoji: '🦫'},
  {type: 'nature', name: 'bat',emoji: '🦇'},
  {type: 'nature', name: 'sloth',emoji: '🦥'},
  {type: 'nature', name: 'otter',emoji: '🦦'},
  {type: 'nature', name: 'hedgehog',emoji: '🦔'},
  {type: 'nature', name: 'skunk',emoji: '🦨'},
  {type: 'nature', name: 'kangaroo',emoji: '🦘'},
  {type: 'nature', name: 'panda_face',emoji: '🐼'},
  {type: 'nature', name: 'snake',emoji: '🐍'},
  {type: 'nature', name: 'bird',emoji: '🐦'},
  {type: 'nature', name: 'baby_chick',emoji: '🐤'},
  {type: 'nature', name: 'hatched_chick',emoji: '🐥'},
  {type: 'nature', name: 'hatching_chick',emoji: '🐣'},
  {type: 'nature', name: 'chicken',emoji: '🐔'},
  {type: 'nature', name: 'turkey',emoji: '🦃'},
  {type: 'nature', name: 'dove',emoji: '🕊️'},
  {type: 'nature', name: 'eagle',emoji: '🦅'},
  {type: 'nature', name: 'duck',emoji: '🦆'},
  {type: 'nature', name: 'swan',emoji: '🦢'},
  {type: 'nature', name: 'owl',emoji: '🦉'},
  {type: 'nature', name: 'dodo',emoji: '🦤'},
  {type: 'nature', name: 'feather',emoji: '🪶'},
  {type: 'nature', name: 'flamingo',emoji: '🦩'},
  {type: 'nature', name: 'peacock',emoji: '🦚'},
  {type: 'nature', name: 'parrot',emoji: '🦜'},
  {type: 'nature', name: 'penguin',emoji: '🐧'},
  {type: 'nature', name: 'crocodile',emoji: '🐊'},
  {type: 'nature', name: 'lizard',emoji: '🦎'},
  {type: 'nature', name: 't-rex',emoji: '🦖'},
  {type: 'nature', name: 'turtle',emoji: '🐢'},
  {type: 'nature', name: 'bug',emoji: '🐛'},
  {type: 'nature', name: 'honeybee',emoji: '🐝'},
  {type: 'nature', name: 'ant',emoji: '🐜'},
  {type: 'nature', name: 'beetle',emoji: '🪲'},
  {type: 'nature', name: 'snail',emoji: '🐌'},
  {type: 'nature', name: 'butterfly',emoji: '🦋'},
  {type: 'nature', name: 'lady_beetle',emoji: '🐞'},
  {type: 'nature', name: 'cricket',emoji: '🦗'},
  {type: 'nature', name: 'cockroach',emoji: '🪳'},
  {type: 'nature', name: 'spider',emoji: '🕷️'},
  {type: 'nature', name: 'spider_web',emoji: '🕸️'},
  {type: 'nature', name: 'scorpion',emoji: '🦂'},
  {type: 'nature', name: 'mosquito',emoji: '🦟'},
  {type: 'nature', name: 'fly',emoji: '🪰'},
  {type: 'nature', name: 'worm',emoji: '🪱'},
  {type: 'nature', name: 'microbe',emoji: '🦠'},
  {type: 'nature', name: 'octopus',emoji: '🐙'},
  {type: 'nature', name: 'tropical_fish',emoji: '🐠'},
  {type: 'nature', name: 'fish',emoji: '🐟'},
  {type: 'nature', name: 'whale',emoji: '🐳'},
  {type: 'nature', name: 'whale2',emoji: '🐋'},
  {type: 'nature', name: 'dolphin',emoji: '🐬'},
  {type: 'nature', name: 'cow2',emoji: '🐄'},
  {type: 'nature', name: 'ram',emoji: '🐏'},
  {type: 'nature', name: 'rat',emoji: '🐀'},
  {type: 'nature', name: 'water_buffalo',emoji: '🐃'},
  {type: 'nature', name: 'tiger2',emoji: '🐅'},
  {type: 'nature', name: 'rabbit2',emoji: '🐇'},
  {type: 'nature', name: 'dragon',emoji: '🐉'},
  {type: 'nature', name: 'goat',emoji: '🐐'},
  {type: 'nature', name: 'rooster',emoji: '🐓'},
  {type: 'nature', name: 'dog2',emoji: '🐕'},
  {type: 'nature', name: 'pig2',emoji: '🐖'},
  {type: 'nature', name: 'mouse2',emoji: '🐁'},
  {type: 'nature', name: 'ox',emoji: '🐂'},
  {type: 'nature', name: 'dragon_face',emoji: '🐲'},
  {type: 'nature', name: 'blowfish',emoji: '🐡'},
  {type: 'nature', name: 'dromedary_camel',emoji: '🐪'},
  {type: 'nature', name: 'leopard',emoji: '🐆'},
  {type: 'nature', name: 'cat2',emoji: '🐈'},
  {type: 'nature', name: 'poodle',emoji: '🐩'},
  {type: 'nature', name: 'chipmunk',emoji: '🐿️'},
  {type: 'nature', name: 'badger',emoji: '🦡'},
  {type: 'nature', name: 'paw_prints',emoji: '🐾'},

  {type: 'nature', name: 'bouquet',emoji: '💐'},
  {type: 'nature', name: 'cherry_blossom',emoji: '🌸'},
  {type: 'nature', name: 'white_flower',emoji: '💮'},
  {type: 'nature', name: 'rosette',emoji: '🏵️'},
  {type: 'nature', name: 'tulip',emoji: '🌷'},
  {type: 'nature', name: 'four_leaf_clover',emoji: '🍀'},
  {type: 'nature', name: 'rose',emoji: '🌹'},
  {type: 'nature', name: 'sunflower',emoji: '🌻'},
  {type: 'nature', name: 'hibiscus',emoji: '🌺'},
  {type: 'nature', name: 'blossom',emoji: '🌼'},
  {type: 'nature', name: 'maple_leaf',emoji: '🍁'},
  {type: 'nature', name: 'leaves',emoji: '🍃'},
  {type: 'nature', name: 'fallen_leaf',emoji: '🍂'},
  {type: 'nature', name: 'herb',emoji: '🌿'},
  {type: 'nature', name: 'mushroom',emoji: '🍄'},
  {type: 'nature', name: 'cactus',emoji: '🌵'},
  {type: 'nature', name: 'palm_tree',emoji: '🌴'},
  {type: 'nature', name: 'evergreen_tree',emoji: '🌲'},
  {type: 'nature', name: 'deciduous_tree',emoji: '🌳'},
  {type: 'nature', name: 'chestnut',emoji: '🌰'},
  {type: 'nature', name: 'seedling',emoji: '🌱'},
  {type: 'nature', name: 'potted_plant',emoji: '🪴'},
  {type: 'nature', name: 'cactus',emoji: '🌵'},
  {type: 'nature', name: 'shamrock',emoji: '☘️'},
  {type: 'nature', name: 'ear_of_rice',emoji: '🌾'},
  {type: 'nature', name: 'shell',emoji: '🐚'},
  {type: 'nature', name: 'globe_with_meridians',emoji: '🌐'},
  {type: 'nature', name: 'sun_with_face',emoji: '🌞'},
  {type: 'nature', name: 'full_moon_with_face',emoji: '🌝'},
  {type: 'nature', name: 'new_moon_with_face',emoji: '🌚'},
  {type: 'nature', name: 'new_moon',emoji: '🌑'},
  {type: 'nature', name: 'waxing_crescent_moon',emoji: '🌒'},
  {type: 'nature', name: 'first_quarter_moon',emoji: '🌓'},
  {type: 'nature', name: 'waxing_gibbous_moon',emoji: '🌔'},
  {type: 'nature', name: 'full_moon',emoji: '🌕'},
  {type: 'nature', name: 'waning_gibbous_moon',emoji: '🌖'},
  {type: 'nature', name: 'last_quarter_moon',emoji: '🌗'},
  {type: 'nature', name: 'waning_crescent_moon',emoji: '🌘'},
  {type: 'nature', name: 'last_quarter_moon_with_face',emoji: '🌜'},
  {type: 'nature', name: 'first_quarter_moon_with_face',emoji: '🌛'},
  {type: 'nature', name: 'moon',emoji: '🌔'},
  {type: 'nature', name: 'earth_africa',emoji: '🌍'},
  {type: 'nature', name: 'earth_americas',emoji: '🌎'},
  {type: 'nature', name: 'earth_asia',emoji: '🌏'},
  {type: 'nature', name: 'volcano',emoji: '🌋'},
  {type: 'nature', name: 'milky_way',emoji: '🌌'},
  {type: 'nature', name: 'partly_sunny',emoji: '⛅'},

  {type: 'objects', name: 'bamboo',emoji: '🎍'},
  {type: 'objects', name: 'gift_heart',emoji: '💝'},
  {type: 'objects', name: 'dolls',emoji: '🎎'},
  {type: 'objects', name: 'school_satchel',emoji: '🎒'},
  {type: 'objects', name: 'mortar_board',emoji: '🎓'},
  {type: 'objects', name: 'flags',emoji: '🎏'},
  {type: 'objects', name: 'fireworks',emoji: '🎆'},
  {type: 'objects', name: 'sparkler',emoji: '🎇'},
  {type: 'objects', name: 'wind_chime',emoji: '🎐'},
  {type: 'objects', name: 'rice_scene',emoji: '🎑'},
  {type: 'objects', name: 'jack_o_lantern',emoji: '🎃'},
  {type: 'objects', name: 'ghost',emoji: '👻'},
  {type: 'objects', name: 'santa',emoji: '🎅'},
  {type: 'objects', name: 'christmas_tree',emoji: '🎄'},
  {type: 'objects', name: 'gift',emoji: '🎁'},
  {type: 'objects', name: 'bell',emoji: '🔔'},
  {type: 'objects', name: 'no_bell',emoji: '🔕'},
  {type: 'objects', name: 'tanabata_tree',emoji: '🎋'},
  {type: 'objects', name: 'tada',emoji: '🎉'},
  {type: 'objects', name: 'confetti_ball',emoji: '🎊'},
  {type: 'objects', name: 'balloon',emoji: '🎈'},
  {type: 'objects', name: 'crystal_ball',emoji: '🔮'},
  {type: 'objects', name: 'cd',emoji: '💿'},
  {type: 'objects', name: 'dvd',emoji: '📀'},
  {type: 'objects', name: 'floppy_disk',emoji: '💾'},
  {type: 'objects', name: 'camera',emoji: '📷'},
  {type: 'objects', name: 'video_camera',emoji: '📹'},
  {type: 'objects', name: 'movie_camera',emoji: '🎥'},
  {type: 'objects', name: 'computer',emoji: '💻'},
  {type: 'objects', name: 'tv',emoji: '📺'},
  {type: 'objects', name: '',emoji: ''},
  {type: 'objects', name: '',emoji: ''},
  {type: 'objects', name: '',emoji: ''},
  {type: 'objects', name: '',emoji: ''},
  {type: 'objects', name: '',emoji: ''},
  {type: 'objects', name: '',emoji: ''},

  {type: 'places', name: 'house',emoji: '🏠'},
  {type: 'places', name: 'house_with_garden',emoji: '🏡'},
  {type: 'places', name: 'school',emoji: '🏫'},
  {type: 'places', name: 'office',emoji: '🏢'},
  {type: 'places', name: 'post_office',emoji: '🏣'},
  {type: 'places', name: 'hospital',emoji: '🏥'},
  {type: 'places', name: 'bank',emoji: '🏦'},
  {type: 'places', name: 'convenience_store',emoji: '🏪'},
  {type: 'places', name: 'love_hotel',emoji: '🏩'},
  {type: 'places', name: 'hotel',emoji: '🏨'},
  {type: 'places', name: 'wedding',emoji: '💒'},
  {type: 'places', name: '',emoji: ''},


  {type: 'symbols', name: 'one',emoji: '1️⃣'},
  {type: 'symbols', name: 'two',emoji: '2️⃣'},
  {type: 'symbols', name: 'three',emoji: '3️⃣'},
  {type: 'symbols', name: 'four',emoji: '4️⃣'},
  {type: 'symbols', name: 'five',emoji: '5️⃣'},
  {type: 'symbols', name: 'six',emoji: '6️⃣'},
  {type: 'symbols', name: 'seven',emoji: '7️⃣'},
  {type: 'symbols', name: 'eight',emoji: '8️⃣'},
  {type: 'symbols', name: 'nine',emoji: '9️⃣'},
  {type: 'symbols', name: 'keycap_ten',emoji: '🔟'},
  {type: 'symbols', name: '1234',emoji: '🔢'},
  {type: 'symbols', name: 'zero',emoji: '0️⃣'},
  {type: 'symbols', name: 'hash',emoji: '#️⃣'},
  {type: 'symbols', name: 'symbols',emoji: '🔣'},
  {type: 'symbols', name: 'arrow_backward',emoji: '◀️'},
  {type: 'symbols', name: 'arrow_down',emoji: '⬇️'},
  {type: 'symbols', name: 'arrow_forward',emoji: '▶️'},
  {type: 'symbols', name: 'arrow_left',emoji: '⬅️'},
  {type: 'symbols', name: 'capital_abcd',emoji: '🔠'},
  {type: 'symbols', name: 'abcd',emoji: '🔡'},
  {type: 'symbols', name: 'abc',emoji: '🔤'},
  {type: 'symbols', name: 'arrow_lower_left',emoji: '↙️'},
  {type: 'symbols', name: 'arrow_lower_right',emoji: '↘️'},
  {type: 'symbols', name: 'arrow_right',emoji: '➡️'},
  {type: 'symbols', name: 'arrow_up',emoji: '⬆️'},
  {type: 'symbols', name: 'arrow_upper_left',emoji: '↖️'},
  {type: 'symbols', name: 'arrow_upper_right',emoji: '↗️'},
  {type: 'symbols', name: 'arrow_double_down',emoji: '⏬'},
  {type: 'symbols', name: 'arrow_double_up',emoji: '⏫'},
  {type: 'symbols', name: 'arrow_down_small',emoji: '🔽'},
  {type: 'symbols', name: 'arrow_heading_down',emoji: '⤵️'},
  {type: 'symbols', name: 'arrow_heading_up',emoji: '⤴️'},
  {type: 'symbols', name: 'leftwards_arrow_with_hook',emoji: '↩️'},
  {type: 'symbols', name: 'arrow_right_hook',emoji: '↪️'},
  {type: 'symbols', name: 'arrow_up_small',emoji: '🔼'},
  {type: 'symbols', name: 'arrows_clockwise',emoji: '🔃'},
  {type: 'symbols', name: 'arrows_counterclockwise',emoji: '🔄'},
  {type: 'symbols', name: 'rewind',emoji: '⏪'},
  {type: 'symbols', name: 'fast_forward',emoji: '⏩'},
  {type: 'symbols', name: 'ok',emoji: '🆗'},
  {type: 'symbols', name: 'twisted_rightwards_arrows',emoji: '🔀'},
  {type: 'symbols', name: 'repeat',emoji: '🔁'},
  {type: 'symbols', name: 'repeat_one',emoji: '🔂'},
  {type: 'symbols', name: 'new',emoji: '🆕'},
  {type: 'symbols', name: 'top',emoji: '🔝'},
  {type: 'symbols', name: 'up',emoji: '🆙'},
  {type: 'symbols', name: 'cool',emoji: '🆒'},
  {type: 'symbols', name: 'free',emoji: '🆓'},
  {type: 'symbols', name: 'ng',emoji: '🆖'},
  {type: 'symbols', name: 'cinema',emoji: '🎦'},
  {type: 'symbols', name: 'koko',emoji: '🈁'},
  {type: 'symbols', name: 'signal_strength',emoji: '📶'},
  {type: 'symbols', name: 'u5272',emoji: '🈹'},
  {type: 'symbols', name: 'u5408',emoji: '🈴'},
  {type: 'symbols', name: 'u55b6',emoji: '🈺'},
  {type: 'symbols', name: 'u6307',emoji: '🈯'},
  {type: 'symbols', name: 'u6708',emoji: '🈷️'},
  {type: 'symbols', name: 'u6709',emoji: '🈶'},
  {type: 'symbols', name: 'u6e80',emoji: '🈵'},
  {type: 'symbols', name: 'u7121',emoji: '🈚'},
  {type: 'symbols', name: 'u7533',emoji: '🈸'},
  {type: 'symbols', name: 'u7a7a',emoji: '🈳'},
  {type: 'symbols', name: 'u7981',emoji: '🈲'},
  {type: 'symbols', name: 'sa',emoji: '🈂️'},
  {type: 'symbols', name: 'restroom',emoji: '🚻'},
  {type: 'symbols', name: 'mens',emoji: '🚹'},
  {type: 'symbols', name: 'womens',emoji: '🚺'},
  {type: 'symbols', name: 'baby_symbol',emoji: '🚼'},
  {type: 'symbols', name: 'no_smoking',emoji: '🚭'},
  {type: 'symbols', name: 'parking',emoji: '🅿️'},
  {type: 'symbols', name: 'wheelchair',emoji: '♿'},
  {type: 'symbols', name: 'metro',emoji: '🚇'},
  {type: 'symbols', name: 'baggage_claim',emoji: '🛄'},
  {type: 'symbols', name: 'accept',emoji: '🉑'},
  {type: 'symbols', name: 'wc',emoji: '🚾'},
  {type: 'symbols', name: 'potable_water',emoji: '🚰'},
  {type: 'symbols', name: 'put_litter_in_its_place',emoji: '🚮'},
  {type: 'symbols', name: 'secret',emoji: '㊙️'},
  {type: 'symbols', name: 'congratulations',emoji: '㊗️'},
  {type: 'symbols', name: 'm',emoji: 'Ⓜ️'},
  {type: 'symbols', name: 'passport_control',emoji: '🛂'},
  {type: 'symbols', name: 'left_luggage',emoji: '🛅'},
  {type: 'symbols', name: 'customs',emoji: '🛃'},
  {type: 'symbols', name: 'ideograph_advantage',emoji: '🉐'},
  {type: 'symbols', name: 'cl',emoji: '🆑'},
  {type: 'symbols', name: 'sos',emoji: '🆘'},
  {type: 'symbols', name: 'id',emoji: '🆔'},
  {type: 'symbols', name: 'no_entry_sign',emoji: '🚫'},
  {type: 'symbols', name: 'underage',emoji: '🔞'},
  {type: 'symbols', name: 'no_mobile_phones',emoji: '📵'},
  {type: 'symbols', name: 'do_not_litter',emoji: '🚯'},
  {type: 'symbols', name: 'non-potable_water',emoji: '🚱'},
  {type: 'symbols', name: 'no_bicycles',emoji: '🚳'},
  {type: 'symbols', name: 'no_pedestrians',emoji: '🚷'},
  {type: 'symbols', name: 'children_crossing',emoji: '🚸'},
  {type: 'symbols', name: 'no_entry',emoji: '⛔'},
  {type: 'symbols', name: 'eight_spoked_asterisk',emoji: '✳️'},
  {type: 'symbols', name: 'eight_pointed_black_star',emoji: '✴️'},
  {type: 'symbols', name: 'heart_decoration',emoji: '💟'},
  {type: 'symbols', name: 'vs',emoji: '🆚'},
  {type: 'symbols', name: 'vibration_mode',emoji: '📳'},
  {type: 'symbols', name: 'mobile_phone_off',emoji: '📴'},
  {type: 'symbols', name: 'chart',emoji: '💹'},
  {type: 'symbols', name: 'currency_exchange',emoji: '💱'},
  {type: 'symbols', name: 'aries',emoji: '♈'},
  {type: 'symbols', name: 'taurus',emoji: '♉'},
  {type: 'symbols', name: 'gemini',emoji: '♊'},
  {type: 'symbols', name: 'cancer',emoji: '♋'},
  {type: 'symbols', name: 'leo',emoji: '♌'},
  {type: 'symbols', name: 'virgo',emoji: '♍'},
  {type: 'symbols', name: 'libra',emoji: '♎'},
  {type: 'symbols', name: 'scorpius',emoji: '♏'},
  {type: 'symbols', name: 'sagittarius',emoji: '♐'},
  {type: 'symbols', name: 'capricorn',emoji: '♑'},
  {type: 'symbols', name: 'aquarius',emoji: '♒'},
  {type: 'symbols', name: 'pisces',emoji: '♓'},
  {type: 'symbols', name: 'ophiuchus',emoji: '⛎'},
  {type: 'symbols', name: 'six_pointed_star',emoji: '🔯'},
  {type: 'symbols', name: 'negative_squared_cross_mark',emoji: '❎'},
  {type: 'symbols', name: 'a',emoji: '🅰️'},
  {type: 'symbols', name: 'b',emoji: '🅱️'},
  {type: 'symbols', name: 'ab',emoji: '🆎'},
  {type: 'symbols', name: 'o2',emoji: '🅾️'},
  {type: 'symbols', name: 'diamond_shape_with_a_dot_inside',emoji: '💠'},
  {type: 'symbols', name: 'recycle',emoji: '♻️'},
  {type: 'symbols', name: 'end',emoji: '🔚'},
  {type: 'symbols', name: 'on',emoji: '🔛'},
  {type: 'symbols', name: 'soon',emoji: '🔜'},
  {type: 'symbols', name: 'clock1',emoji: '🕐'},
  {type: 'symbols', name: 'clock130',emoji: '🕜'},
  {type: 'symbols', name: 'clock10',emoji: '🕙'},
  {type: 'symbols', name: 'clock1030',emoji: '🕥'},
  {type: 'symbols', name: 'clock11',emoji: '🕚'},
  {type: 'symbols', name: 'clock1130',emoji: '🕦'},
  {type: 'symbols', name: 'clock12',emoji: '🕛'},
  {type: 'symbols', name: 'clock1230',emoji: '🕧'},
  {type: 'symbols', name: 'clock2',emoji: '🕑'},
  {type: 'symbols', name: 'clock230',emoji: '🕝'},
  {type: 'symbols', name: 'clock3',emoji: '🕒'},
  {type: 'symbols', name: 'clock330',emoji: '🕞'},
  {type: 'symbols', name: 'clock4',emoji: '🕓'},
  {type: 'symbols', name: 'clock430',emoji: '🕟'},
  {type: 'symbols', name: 'clock5',emoji: '🕔'},
  {type: 'symbols', name: 'clock530',emoji: '🕠'},
  {type: 'symbols', name: 'clock6',emoji: '🕕'},
  {type: 'symbols', name: 'clock630',emoji: '🕡'},
  {type: 'symbols', name: 'clock7',emoji: '🕖'},
  {type: 'symbols', name: 'clock730',emoji: '🕢'},
  {type: 'symbols', name: 'clock8',emoji: '🕗'},
  {type: 'symbols', name: 'clock830',emoji: '🕣'},
  {type: 'symbols', name: 'clock9',emoji: '🕘'},
  {type: 'symbols', name: 'clock930',emoji: '🕤'},
  {type: 'symbols', name: 'hourglass',emoji: '⌛'},
  {type: 'symbols', name: 'hourglass_flowing_sand',emoji: '⏳'},
  {type: 'symbols', name: 'watch',emoji: '⌚'},
  {type: 'symbols', name: 'alarm_clock',emoji: '⏰'},
  {type: 'symbols', name: 'stopwatch',emoji: '⏱️'},
  {type: 'symbols', name: 'timer_clock',emoji: '⏲️'},
  {type: 'symbols', name: 'mantelpiece_clock',emoji: '🕰️'},
  {type: 'symbols', name: 'heavy_dollar_sign',emoji: '💲'},
  {type: 'symbols', name: 'copyright',emoji: '©️'},
  {type: 'symbols', name: 'registered',emoji: '®️'},
  {type: 'symbols', name: 'tm',emoji: '™️'},
  {type: 'symbols', name: 'x',emoji: '❌'},
  {type: 'symbols', name: 'heavy_exclamation_mark',emoji: '❗'},
  {type: 'symbols', name: 'bangbang',emoji: '‼️'},
  {type: 'symbols', name: 'interrobang',emoji: '⁉️'},
  {type: 'symbols', name: 'o',emoji: '⭕'},
  {type: 'symbols', name: 'heavy_multiplication_x',emoji: '✖️'},
  {type: 'symbols', name: 'heavy_plus_sign',emoji: '➕'},
  {type: 'symbols', name: 'heavy_minus_sign',emoji: '➖'},
  {type: 'symbols', name: 'heavy_division_sign',emoji: '➗'},
  {type: 'symbols', name: 'heavy_check_mark',emoji: '✔️'},
  {type: 'symbols', name: 'ballot_box_with_check',emoji: '☑️'},
  {type: 'symbols', name: 'white_check_mark',emoji: '✅'},
  {type: 'symbols', name: '100',emoji: '💯'},
  {type: 'symbols', name: 'radio_button',emoji: '🔘'},
  {type: 'symbols', name: 'link',emoji: '🔗'},
  {type: 'symbols', name: 'curly_loop',emoji: '➰'},
  {type: 'symbols', name: 'wavy_dash',emoji: '〰️'},
  {type: 'symbols', name: 'part_alternation_mark',emoji: '〽️'},
  {type: 'symbols', name: 'trident',emoji: '🔱'},
  {type: 'symbols', name: 'black_square_button',emoji: '🔲'},
  {type: 'symbols', name: 'white_square_button',emoji: '🔳'},
  {type: 'symbols', name: 'black_circle',emoji: '⚫'},
  {type: 'symbols', name: 'white_circle',emoji: '⚪'},
  {type: 'symbols', name: 'red_circle',emoji: '🔴'},
  {type: 'symbols', name: 'large_blue_circle',emoji: '🔵'},
  {type: 'symbols', name: 'large_blue_diamond',emoji: '🔷'},
  {type: 'symbols', name: 'large_orange_diamond',emoji: '🔶'},
  {type: 'symbols', name: 'small_blue_diamond',emoji: '🔹'},
  {type: 'symbols', name: 'small_orange_diamond',emoji: '🔸'},
  {type: 'symbols', name: 'small_red_triangle',emoji: '🔺'},
  {type: 'symbols', name: 'small_red_triangle_down',emoji: '🔻'},

];

export const getEmojiFromText = (text: string) => {

    const match = emojiList.find((item) => item.name === text)
    if(match !== undefined)
    {
        return match.emoji
    }
    else
    {
        return text
    }
}

export const getEmojiList = () => {
    return(emojiList)
}
