
const emojiList = [
  {type: 'people', name: 'smile', emoji: '😄'}, 
  {type: 'people', name: 'laughing', emoji: '😆'},
  {type: 'people', name: 'blush', emoji: '😊'},
  {type: 'people', name: 'smiley', emoji: '😃'},
  {type: 'people', name: 'smirk', emoji: '😏'},
  {type: 'people', name: 'heart_eyes', emoji: '😍'},
  {type: 'people', name: 'kissing_heart', emoji: '😘'},
  {type: 'people', name: 'kissing_closed_eyes', emoji: '😚'},
  {type: 'people', name: 'flushed', emoji: '😳'},
  {type: 'people', name: 'relieved', emoji: '😌'},
  {type: 'people', name: 'grin', emoji: '😁'},
  {type: 'people', name: 'wink',emoji: '😉'},
  {type: 'people', name: 'stuck_out_tongue', emoji: '😛'},
  {type: 'people', name: 'sleeping', emoji: '😴'},
  {type: 'people', name: 'worried', emoji: '😟'},
  {type: 'people', name: 'open_mouth', emoji: '😮'},
  {type: 'people', name: 'confused', emoji: '😕'},
  {type: 'people', name: 'expressionless', emoji: '😑'},
  {type: 'people', name: 'sweat_smile', emoji: '😅'},
  {type: 'people', name: 'weary', emoji: '😩'},
  {type: 'people', name: 'pensive', emoji: '😔'},
  {type: 'people', name: 'disappointed', emoji: '😞'},
  {type: 'people', name: 'fearful', emoji: '😨'},
  {type: 'people', name: 'cry', emoji: '😢'},
  {type: 'people', name: 'sob',emoji: '😭'},
  {type: 'people', name: 'joy',emoji: '😂'},
  {type: 'people', name: 'scream',emoji: '😱'},
  {type: 'people', name: 'angry',emoji: '😠'},
  {type: 'people', name: 'rage',emoji: '😡'},
  {type: 'people', name: 'triumph',emoji: '😤'},
  {type: 'people', name: 'sleepy',emoji: '😪'},
  {type: 'people', name: 'yum',emoji: '😋'},
  {type: 'people', name: 'mask',emoji: '😷'},
  {type: 'people', name: 'sunglasses',emoji: '😎'},
  {type: 'people', name: 'dizzy_face',emoji: '😵'},
  {type: 'people', name: 'innocent',emoji: '😇'},
  {type: 'people', name: 'alien',emoji: '👽'},

  {type: 'people', name: 'walking',emoji: '🚶'},
  {type: 'people', name: 'runner',emoji: '🏃'},
  {type: 'people', name: 'couple',emoji: '👫'},
  {type: 'people', name: 'family',emoji: '👪'},
  {type: 'people', name: 'dancer',emoji: '💃'},
  {type: 'people', name: 'dancers',emoji: '👯'},
  {type: 'people', name: 'raising_hand',emoji: '🙋'},
  {type: 'people', name: 'bow',emoji: '🙇'},
  {type: 'people', name: 'boy',emoji: '👦'},
  {type: 'people', name: 'girl',emoji: '👧'},
  {type: 'people', name: 'woman',emoji: '👩'},
  {type: 'people', name: 'man',emoji: '👨'},
  {type: 'people', name: 'baby',emoji: '👶'},
  {type: 'people', name: 'older_woman',emoji: '👵'},
  {type: 'people', name: 'older_man',emoji: '👴'},
  {type: 'people', name: 'cop',emoji: '👮'},
  {type: 'people', name: 'detective',emoji: '🕵️'},
  {type: 'people', name: 'mermaid',emoji: '🧜‍♀️'},
  {type: 'people', name: 'person_fencing',emoji: '🤺'},
  {type: 'people', name: 'selfie',emoji: '🤳'},
  {type: 'people', name: 'angel',emoji: '👼'},
  {type: 'people', name: 'smiley_cat',emoji: '😺'},
  {type: 'people', name: 'smile_cat',emoji: '😸'},
  {type: 'people', name: 'heart_eyes_cat',emoji: '😻'},
  {type: 'people', name: 'kissing_cat',emoji: '😽'},
  {type: 'people', name: 'smirk_cat',emoji: '😼'},
  {type: 'people', name: 'scream_cat',emoji: '🙀'},
  {type: 'people', name: 'crying_cat_face',emoji: '😿'},
  {type: 'people', name: 'joy_cat',emoji: '😹'},
  {type: 'people', name: 'pouting_cat',emoji: '😾'},
  {type: 'people', name: 'japanese_ogre',emoji: '👹'},
  {type: 'people', name: 'japanese_goblin',emoji: '👺'},
  {type: 'people', name: 'see_no_evil',emoji: '🙈'},
  {type: 'people', name: 'hear_no_evil',emoji: '🙉'},
  {type: 'people', name: 'speak_no_evil',emoji: '🙊'},
  {type: 'people', name: 'guardsman',emoji: '💂‍♂️'},
  {type: 'people', name: 'skull',emoji: '💀'},
  {type: 'people', name: 'feet',emoji: '🐾'},
  {type: 'people', name: 'lips',emoji: '👄'},
  {type: 'people', name: 'kiss',emoji: '💋'},
  {type: 'people', name: 'droplet',emoji: '💧'},
  {type: 'people', name: 'ear',emoji: '👂'},
  {type: 'people', name: 'eyes',emoji: '👀'},
  {type: 'people', name: 'eye',emoji: '👁️'},
  {type: 'people', name: 'nose',emoji: '👃'},
  {type: 'people', name: 'tongue',emoji: '👅'},
  {type: 'people', name: 'love_letter',emoji: '💌'},
  {type: 'people', name: 'speech_balloon',emoji: '💬'},
  {type: 'people', name: 'thought_balloon',emoji: '💭'},

  {type: 'people', name: '+1',emoji: '👍'},
  {type: 'people', name: 'thumbsup',emoji: '👍'},
  {type: 'people', name: '-1',emoji: '👎'},
  {type: 'people', name: 'thumbsdown',emoji: '👎'},
  {type: 'people', name: 'ok_hand',emoji: '👌'},
  {type: 'people', name: 'wave',emoji: '👋'},
  {type: 'people', name: 'punch',emoji: '👊'},
  {type: 'people', name: 'v',emoji: '✌️'},
  {type: 'people', name: 'open_hands',emoji: '👐'},
  {type: 'people', name: 'point_up',emoji: '☝️'},
  {type: 'people', name: 'point_down',emoji: '👇'},
  {type: 'people', name: 'raised_hands',emoji: '🙌'},
  {type: 'people', name: 'pray',emoji: '🙏'},
  {type: 'people', name: 'clap',emoji: '👏'},
  {type: 'people', name: 'muscle',emoji: '💪'},
  {type: 'people', name: 'metal',emoji: '🤘'},
  {type: 'people', name: 'fu',emoji: '🖕'},

  {type: 'people', name: 'fire',emoji: '🔥'},
  {type: 'people', name: 'poop',emoji: '💩'},
  {type: 'people', name: 'yellow_heart',emoji: '💛'},
  {type: 'people', name: 'blue_heart',emoji: '💙'},
  {type: 'people', name: 'purple_heart',emoji: '💜'},
  {type: 'people', name: 'heart',emoji: '❤️'},
  {type: 'people', name: 'green_heart',emoji: '💚'},
  {type: 'people', name: 'broken_heart',emoji: '💔'},
  {type: 'people', name: 'heartbeat',emoji: '💓'},
  {type: 'people', name: 'heartpulse',emoji: '💗'},
  {type: 'people', name: 'two_hearts',emoji: '💕'},
  {type: 'people', name: 'cupid',emoji: '💘'},
  {type: 'people', name: 'sparkling_heart',emoji: '💖'},
  {type: 'people', name: 'sparkles',emoji: '✨'},
  {type: 'people', name: 'star',emoji: '⭐'},
  {type: 'people', name: 'star2',emoji: '🌟'},
  {type: 'people', name: 'dizzy',emoji: '💫'},
  {type: 'people', name: 'boom',emoji: '💥'},
  {type: 'people', name: 'anger',emoji: '💢'},
  {type: 'people', name: 'exclamation',emoji: '❗'},
  {type: 'people', name: 'question',emoji: '❓'},
  {type: 'people', name: 'grey_exclamation',emoji: '❕'},
  {type: 'people', name: 'grey_question',emoji: '❔'},
  {type: 'people', name: 'zzz',emoji: '💤'},
  {type: 'people', name: 'dash',emoji: '💨'},
  {type: 'people', name: 'sweat_drops',emoji: '💦'},
  {type: 'people', name: 'notes',emoji: '🎶'},
  {type: 'people', name: 'musical_note',emoji: '🎵'},

  {type: 'nature', name: 'sunny',emoji: '☀️'},
  {type: 'nature', name: 'umbrella',emoji: '☔'},
  {type: 'nature', name: 'cloud',emoji: '☁️'},
  {type: 'nature', name: 'snowflake',emoji: '❄️'},
  {type: 'nature', name: 'snowman',emoji: '⛄'},
  {type: 'nature', name: 'zap',emoji: '⚡'},
  {type: 'nature', name: 'cyclone',emoji: '🌀'},
  {type: 'nature', name: 'foggy',emoji: '🌁'},
  {type: 'nature', name: 'ocean',emoji: '🌊'},
  {type: 'nature', name: 'cat',emoji: '🐱'},
  {type: 'nature', name: 'dog',emoji: '🐶'},
  {type: 'nature', name: 'mouse',emoji: '🐭'},
  {type: 'nature', name: 'hamster',emoji: '🐹'},
  {type: 'nature', name: 'rabbit',emoji: '🐰'},
  {type: 'nature', name: 'wolf',emoji: '🐺'},
  {type: 'nature', name: 'frog',emoji: '🐸'},
  {type: 'nature', name: 'tiger',emoji: '🐯'},
  {type: 'nature', name: 'koala',emoji: '🐨'},
  {type: 'nature', name: 'bear',emoji: '🐻'},
  {type: 'nature', name: 'pig',emoji: '🐷'},
  {type: 'nature', name: 'pig_nose',emoji: '🐽'},
  {type: 'nature', name: 'cow',emoji: '🐮'},
  {type: 'nature', name: 'boar',emoji: '🐗'},
  {type: 'nature', name: 'monkey_face',emoji: '🐵'},
  {type: 'nature', name: 'monkey',emoji: '🐒'},
  {type: 'nature', name: 'horse',emoji: '🐴'},
  {type: 'nature', name: 'racehorse',emoji: '🐎'},
  {type: 'nature', name: 'camel',emoji: '🐫'},
  {type: 'nature', name: 'sheep',emoji: '🐑'},
  {type: 'nature', name: 'elephant',emoji: '🐘'},
  {type: 'nature', name: 'panda_face',emoji: '🐼'},
  {type: 'nature', name: 'snake',emoji: '🐍'},
  {type: 'nature', name: 'bird',emoji: '🐦'},
  {type: 'nature', name: 'baby_chick',emoji: '🐤'},
  {type: 'nature', name: 'hatched_chick',emoji: '🐥'},
  {type: 'nature', name: 'hatching_chick',emoji: '🐣'},
  {type: 'nature', name: 'chicken',emoji: '🐔'},
  {type: 'nature', name: 'penguin',emoji: '🐧'},
  {type: 'nature', name: 'turtle',emoji: '🐢'},
  {type: 'nature', name: 'bug',emoji: '🐛'},
  {type: 'nature', name: 'honeybee',emoji: '🐝'},
  {type: 'nature', name: 'ant',emoji: '🐜'},
  {type: 'nature', name: 'beetle',emoji: '🪲'},
  {type: 'nature', name: 'snail',emoji: '🐌'},
  {type: 'nature', name: 'octopus',emoji: '🐙'},
  {type: 'nature', name: 'tropical_fish',emoji: '🐠'},
  {type: 'nature', name: 'fish',emoji: '🐟'},
  {type: 'nature', name: 'whale',emoji: '🐳'},
  {type: 'nature', name: 'whale2',emoji: '🐋'},
  {type: 'nature', name: 'dolphin',emoji: '🐬'},
  {type: 'nature', name: 'cow2',emoji: '🐄'},
  {type: 'nature', name: 'ram',emoji: '🐏'},
  {type: 'nature', name: 'rat',emoji: '🐀'},
  {type: 'nature', name: 'water_buffalo',emoji: '🐃'},
  {type: 'nature', name: 'tiger2',emoji: '🐅'},
  {type: 'nature', name: 'rabbit2',emoji: '🐇'},
  {type: 'nature', name: 'dragon',emoji: '🐉'},
  {type: 'nature', name: 'goat',emoji: '🐐'},
  {type: 'nature', name: 'rooster',emoji: '🐓'},
  {type: 'nature', name: 'dog2',emoji: '🐕'},
  {type: 'nature', name: 'pig2',emoji: '🐖'},
  {type: 'nature', name: 'mouse2',emoji: '🐁'},
  {type: 'nature', name: 'ox',emoji: '🐂'},
  {type: 'nature', name: 'dragon_face',emoji: '🐲'},
  {type: 'nature', name: 'blowfish',emoji: '🐡'},
  {type: 'nature', name: 'crocodile',emoji: '🐊'},
  {type: 'nature', name: 'dromedary_camel',emoji: '🐪'},
  {type: 'nature', name: 'leopard',emoji: '🐆'},
  {type: 'nature', name: 'cat2',emoji: '🐈'},
  {type: 'nature', name: 'poodle',emoji: '🐩'},
  {type: 'nature', name: 'chipmunk',emoji: '🐿️'},
  {type: 'nature', name: 'badger',emoji: '🦡'},
  {type: 'nature', name: 'paw_prints',emoji: '🐾'},
  {type: 'nature', name: 'bouquet',emoji: '💐'},
  {type: 'nature', name: 'cherry_blossom',emoji: '🌸'},
  {type: 'nature', name: 'tulip',emoji: '🌷'},
  {type: 'nature', name: 'four_leaf_clover',emoji: '🍀'},
  {type: 'nature', name: 'rose',emoji: '🌹'},
  {type: 'nature', name: 'sunflower',emoji: '🌻'},
  {type: 'nature', name: 'hibiscus',emoji: '🌺'},
  {type: 'nature', name: 'maple_leaf',emoji: '🍁'},
  {type: 'nature', name: 'leaves',emoji: '🍃'},
  {type: 'nature', name: 'fallen_leaf',emoji: '🍂'},
  {type: 'nature', name: 'herb',emoji: '🌿'},
  {type: 'nature', name: 'mushroom',emoji: '🍄'},
  {type: 'nature', name: 'cactus',emoji: '🌵'},
  {type: 'nature', name: 'palm_tree',emoji: '🌴'},
  {type: 'nature', name: 'evergreen_tree',emoji: '🌲'},
  {type: 'nature', name: 'deciduous_tree',emoji: '🌳'},
  {type: 'nature', name: 'chestnut',emoji: '🌰'},
  {type: 'nature', name: 'seeding',emoji: '🌱'},
  {type: 'nature', name: 'blossom',emoji: '🌼'},
  {type: 'nature', name: 'ear_of_rice',emoji: '🌾'},
  {type: 'nature', name: 'shell',emoji: '🐚'},
  {type: 'nature', name: 'globe_with_meridians',emoji: '🌐'},
  {type: 'nature', name: 'sun_with_face',emoji: '🌞'},
  {type: 'nature', name: 'full_moon_with_face',emoji: '🌝'},
  {type: 'nature', name: 'new_moon_with_face',emoji: '🌚'},
  {type: 'nature', name: 'new_moon',emoji: '🌑'},
  {type: 'nature', name: 'waxing_crescent_moon',emoji: '🌒'},
  {type: 'nature', name: 'first_quarter_moon',emoji: '🌓'},
  {type: 'nature', name: 'waxing_gibbous_moon',emoji: '🌔'},
  {type: 'nature', name: 'full_moon',emoji: '🌕'},
  {type: 'nature', name: 'waning_gibbous_moon',emoji: '🌖'},
  {type: 'nature', name: 'last_quarter_moon',emoji: '🌗'},
  {type: 'nature', name: 'waning_crescent_moon',emoji: '🌘'},
  {type: 'nature', name: 'last_quarter_moon_with_face',emoji: '🌜'},
  {type: 'nature', name: 'first_quarter_moon_with_face',emoji: '🌛'},
  {type: 'nature', name: 'moon',emoji: '🌔'},
  {type: 'nature', name: 'earth_africa',emoji: '🌍'},
  {type: 'nature', name: 'earth_americas',emoji: '🌎'},
  {type: 'nature', name: 'earth_asia',emoji: '🌏'},
  {type: 'nature', name: 'volcano',emoji: '🌋'},
  {type: 'nature', name: 'milky_way',emoji: '🌌'},
  {type: 'nature', name: 'partly_sunny',emoji: '⛅'},

  {type: 'objects', name: 'bamboo',emoji: '🎍'},
  {type: 'objects', name: 'gift_heart',emoji: '💝'},
  {type: 'objects', name: 'dolls',emoji: '🎎'},




];

export const getEmojiFromText = (text: string) => {

    const match = emojiList.find((item) => item.name === text)
    if(match !== undefined)
    {
        return match.emoji
    }
    else
    {
        return text
    }
}

export const getEmojiList = () => {
    return(emojiList)
}
